"""
Completion Wits dataset column names
"""

ID	= "_id"
VERSION	= "version"
PROVIDER	= "provider"
COLLECTION	= "collection"
TIMESTAMP	= "timestamp"
ASSET_ID	= "asset_id"
COMPANY_ID	= "company_id"
STAGE_NUMBER	= "stage_number"
CLEAN_FLOW_RATE_IN_STREAMED	= "clean_flow_rate_in_streamed"
TOTAL_CLEAN_VOLUME_IN_STREAMED	= "total_clean_volume_in_streamed"
TOTAL_SLURRY_VOLUME_IN_STREAMED	= "total_slurry_volume_in_streamed"
PROPPANT_1_MASS_STREAMED	= "proppant_1_mass_streamed"
ELAPSED_TIME	= "elapsed_time"
CLEAN_FLOW_RATE_IN	= "clean_flow_rate_in"
TOTAL_CLEAN_VOLUME_IN	= "total_clean_volume_in"
TOTAL_SLURRY_VOLUME_IN	= "total_slurry_volume_in"
TOTAL_CHEMICAL_RATE_IN	= "total_chemical_rate_in"
TOTAL_FRICTION_REDUCER	= "total_friction_reducer"
TOTAL_PROPPANT_CONCENTRATION	= "total_proppant_concentration"
TOTAL_PROPPANT_MASS	= "total_proppant_mass"
BOTTOMHOLE_PROPPANT_CONCENTRATION	= "bottomhole_proppant_concentration"
HYDROSTATIC_PRESSURE	= "hydrostatic_pressure"
INVERSE_HYDROSTATIC_PRESSURE	= "inverse_hydrostatic_pressure"
PIPE_FRICTIONAL_PRESSURE_LOSS	= "pipe_frictional_pressure_loss"
NWB_FRICTIONAL_PRESSURE_LOSS	= "nwb_frictional_pressure_loss"
BOTTOMHOLE_PRESSURE	= "bottomhole_pressure"
NET_PRESSURE	= "net_pressure"
HYDRAULIC_HORSE_POWER	= "hydraulic_horse_power"
FRICTION_REDUCER	= "friction_reducer"
BIOCIDE	= "biocide"
PROPPANT_1_CONCENTRATION	= "proppant_1_concentration"
PROPPANT_1_MASS	= "proppant_1_mass"
WELLHEAD_PRESSURE	= "wellhead_pressure"
SLURRY_FLOW_RATE_IN	= "slurry_flow_rate_in"
EXTRA_CLEAN_FLUID	= "extra_clean_fluid"
FRICTION_REDUCER	= "friction_reducer"
BIOCIDE	= "biocide"
TOTAL_FRICTION_REDUCER	= "total_friction_reducer"
TIMESTAMP	= "timestamp"
IS_VALID	= "is_valid"
C4H_ZIPPER_GREEN	= "4h zipper green"
C3H_ZIPPER_RED	= "3h zipper red"
C11H_ZIPPER_YELLOW	= "11h zipper yellow"
PUMPSIDE_PRESSURE	= "pumpside_pressure"
C1H_ZIPPER_WHITE	= "1h zipper white"
C2H_ZIPPER_BLUE	= "2h zipper blue"
C5H_ZIPPER	= "5h zipper"
DATE = "date"
D_WELLHEAD_PRESSURE = "d_wellhead_pressure"
D2_WELLHEAD_PRESSURE = "d2_wellhead_pressure"
D_SLURRY_FLOW_RATE = "d_slurry_flow_rate"
D2_SLURRY_FLOW_RATE = "d2_slurry_flow_rate"
D_TOTAL_PROPPANT_CONC = "d_total_proppant_conc"
D2_TOTAL_PROPPANT_CONC = "d2_total_proppant_conc"
A_D_WELLHEAD_PRESSURE = "a_d_wellhead_pressure"


